### ISSUE TITLE
8.1.2 ImportError: libnetcdf.so.13

### ISSUE THREAD

**Issue by banesullivan** [conda-forge/vtk-feedstock#85]
The VTK installed during our feedstock build for PyVista is failing when trying to import the VTK installed from this feedstock. I have no idea why this isn't working, any help would be greatly appreciated.

- PyVista's feedstock: https://github.com/conda-forge/pyvista-feedstock/
- Failing PR: https://github.com/conda-forge/pyvista-feedstock/pull/1

Traceback from failed build (happens on `import vtk`):

```txt
import: 'pyvista'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pyvista_1558161017408/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/vtk/vtkIOExodus.py", line 5, in <module>
    from .vtkIOExodusPython import *
ImportError: libnetcdf.so.13: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/pyvista_1558161017408/test_tmp/run_test.py", line 2, in <module>
    import pyvista
  File "/home/conda/feedstock_root/build_artifacts/pyvista_1558161017408/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/pyvista/__init__.py", line 3, in <module>
    from pyvista.plotting import *
  File "/home/conda/feedstock_root/build_artifacts/pyvista_1558161017408/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/pyvista/plotting.py", line 14, in <module>
    import vtk
  File "/home/conda/feedstock_root/build_artifacts/pyvista_1558161017408/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/vtk/__init__.py", line 68, in <module>
    from .vtkIOExodus import *
  File "/home/conda/feedstock_root/build_artifacts/pyvista_1558161017408/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.7/site-packages/vtk/vtkIOExodus.py", line 9, in <module>
    from vtkIOExodusPython import *
ModuleNotFoundError: No module named 'vtkIOExodusPython'
```

**Comment by grlee77** [comment]
I can reproduce the same problem when building the recipe locally. If I remove the VTK <8.1.2 pinning then the problem goes away for me.

If PyVista does not have known problems with VTK 8.2, I would recommend trying that. If you really need 8.1.2 specifically, we will have to look into it more and maybe make a 8.1.2 branch with a new build.

**Comment by grlee77** [comment]
It looks like Homebrew had also encountered this same import error in the past:
https://github.com/Homebrew/homebrew-science/issues/5173

**Comment by grlee77** [comment]
I looked back in the VTK build logs when 8.1.2 was built with the new compilers and it was using an older netcdf (4.6.2) which had a `libnetcdf.so.13`.
specifically the following line in the log:
```INFO (vtk,lib/libvtkIONetCDF-8.1.so.1): Needed DSO lib/libnetcdf.so.13 found in conda-forge::libnetcdf-4.6.2-hbdf4f91_1001```

However, in the pyvista feedstock [libnetcdf 4.6.3 is being pulled in](
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=36002&view=logs&jobId=e018f978-a0ce-53fb-9fb6-ffd586bfca01&taskId=2e5085ab-c8db-53b1-698d-462b17aa434f&lineStart=794&lineEnd=795&colStart=1&colEnd=1)

which has a `libnetcdf.so.15` instead.

Strangely, the [conda-forge pinning](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/2fafb445f41c91e5e0905a28b5b377c8ef9d88a0/recipe/conda_build_config.yaml#L459-L460) seems to be to 4.6.2, so I'm not sure why the test is trying to run win 4.6.3 instead?

**Comment by grlee77** [comment]
Indeed, a change in the precision of `libnetcdf` pinning seems to be the issue. In March, the pinning was tightened:
https://github.com/conda-forge/conda-forge-pinning-feedstock/commit/29a852acfa8c8592d14142cda77e5a0c5be01de2#diff-8926f6e7808be490ec92ac38016ab868

VTK 8.1.2 was built before that was done, so it has the issue while 8.2 does not. So to fix this we would need to make a new build of 8.1.2.

**Comment by banesullivan** [comment]
conda-forge/pyvista-feedstock#1 is fixed by removing the limit on VTK and using 8.2.0, but we'd greatly appreciate a way to stably install 8.1.2 from this feedstock if you all could implement it

**Comment by grlee77** [comment]
> we'd greatly appreciate a way to stably install 8.1.2 from this feedstock if you all could implement it

A workaround for now is to enforce compatible versions for 8.1.2 via:

```conda install -c conda-forge pyvista "vtk=8.1.2" "libnetcdf=4.6.2"```

**Comment by banesullivan** [comment]
Ah perfect, thanks @grlee77

**Comment by TschonnyCache** [comment]
I still have this problem (ImportError: libnetcdf.so.13: cannot open shared object file: No such file or directory) 
when trying to import vtk (with vtk 8.2. isntalled via conda on a fresh ubuntu vm)

**Comment by sreedharu** [comment]
It worked @grlee77
